// <auto-generated />
using AppCrud.Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppCrud.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("AppCrud.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Tecnología",
                            Name = "Mouse Gamer",
                            Price = 150000m,
                            Sku = "SKU-001",
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Category = "Tecnología",
                            Name = "Teclado Mecánico",
                            Price = 250000m,
                            Sku = "SKU-002",
                            Stock = 5
                        },
                        new
                        {
                            Id = 3,
                            Category = "Tecnología",
                            Name = "Monitor 24",
                            Price = 800000m,
                            Sku = "SKU-003",
                            Stock = 7
                        },
                        new
                        {
                            Id = 4,
                            Category = "Audio",
                            Name = "Audífonos",
                            Price = 120000m,
                            Sku = "SKU-004",
                            Stock = 15
                        },
                        new
                        {
                            Id = 5,
                            Category = "Muebles",
                            Name = "Silla Gamer",
                            Price = 950000m,
                            Sku = "SKU-005",
                            Stock = 3
                        });
                });

            modelBuilder.Entity("AppCrud.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Pepito",
                            LastName = "Perez",
                            PasswordHash = "$2a$11$VjwH/CEmfdKTEJBdAj242OVDkWMoxu7RiKvPAJ.aahklAKMn725Ey",
                            Username = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
